/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;
import org.jooq.mcve.tables.FlywaySchemaHistory;
import org.jooq.mcve.tables.Issue_9679;


/**
 * A class modelling indexes of tables of the <code>mcve</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_PK = Indexes0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_S_IDX;
    public static final Index ISSUE_9679_PKEY = Indexes0.ISSUE_9679_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index FLYWAY_SCHEMA_HISTORY_PK = Internal.createIndex("flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
        public static Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex("flyway_schema_history_s_idx", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
        public static Index ISSUE_9679_PKEY = Internal.createIndex("issue_9679_pkey", Issue_9679.ISSUE_9679, new OrderField[] { Issue_9679.ISSUE_9679.ID }, true);
    }
}
