/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.jooq.mcve.tables.FlywaySchemaHistory;
import org.jooq.mcve.tables.Issue_9679;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mcve extends SchemaImpl {

    private static final long serialVersionUID = -2029325708;

    /**
     * The reference instance of <code>mcve</code>
     */
    public static final Mcve MCVE = new Mcve();

    /**
     * The table <code>mcve.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = org.jooq.mcve.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>mcve.issue_9679</code>.
     */
    public final Issue_9679 ISSUE_9679 = org.jooq.mcve.tables.Issue_9679.ISSUE_9679;

    /**
     * No further instances allowed
     */
    private Mcve() {
        super("mcve", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ISSUE_9679_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Issue_9679.ISSUE_9679);
    }
}
