/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve;


import org.jooq.mcve.tables.FlywaySchemaHistory;
import org.jooq.mcve.tables.Issue_9679;


/**
 * Convenience access to all tables in mcve
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>mcve.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>mcve.issue_9679</code>.
     */
    public static final Issue_9679 ISSUE_9679 = Issue_9679.ISSUE_9679;
}
