/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.tables.records;


import binding.MyPojo;

import java.util.List;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.mcve.tables.Issue_9679;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Issue_9679Record extends UpdatableRecordImpl<Issue_9679Record> implements Record2<Integer, List<MyPojo>> {

    private static final long serialVersionUID = -1517779161;

    /**
     * Setter for <code>mcve.issue_9679.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mcve.issue_9679.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mcve.issue_9679.payload</code>.
     */
    public void setPayload(List<MyPojo> value) {
        set(1, value);
    }

    /**
     * Getter for <code>mcve.issue_9679.payload</code>.
     */
    public List<MyPojo> getPayload() {
        return (List<MyPojo>) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, List<MyPojo>> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, List<MyPojo>> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Issue_9679.ISSUE_9679.ID;
    }

    @Override
    public Field<List<MyPojo>> field2() {
        return Issue_9679.ISSUE_9679.PAYLOAD;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public List<MyPojo> component2() {
        return getPayload();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public List<MyPojo> value2() {
        return getPayload();
    }

    @Override
    public Issue_9679Record value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public Issue_9679Record value2(List<MyPojo> value) {
        setPayload(value);
        return this;
    }

    @Override
    public Issue_9679Record values(Integer value1, List<MyPojo> value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Issue_9679Record
     */
    public Issue_9679Record() {
        super(Issue_9679.ISSUE_9679);
    }

    /**
     * Create a detached, initialised Issue_9679Record
     */
    public Issue_9679Record(Integer id, List<MyPojo> payload) {
        super(Issue_9679.ISSUE_9679);

        set(0, id);
        set(1, payload);
    }
}
